stages:
  data_ingestion:
    cmd: python src\Car_Price_Pred\components\data_ingestion.py
    deps: 
     - src\Car_Price_Pred\components\data_ingestion.py
     - config\config.yaml
    outs:
     - artifacts\data_ingestion\data.zip
     - artifacts\data_ingestion\status.txt
     - artifacts\data_ingestion\taxi_trip_pricing.csv



  data_transformation:
    cmd: python src\Car_Price_Pred\components\data_transformation.py
    deps:
     - src\Car_Price_Pred\components\data_ingestion.py
     - config\config.yaml
     - params.yaml
    outs:
     - artifacts\data_transformation\test_data.csv
     - artifacts\data_transformation\train_data.csv


  model_training:
    cmd: python src\Car_Price_Pred\components\model_training.py
    deps:
     - src\Car_Price_Pred\components\data_transformation.py
     - config\config.yaml
     - params.yaml
    outs:
     - artifacts\model_training\decision_tree.joblib
     - artifacts\model_training\lasso.joblib
     - artifacts\model_training\linear_regression.joblib
     - artifacts\model_training\neighbors.joblib
     - artifacts\model_training\params.json
     - artifacts\model_training\random_forest.joblib
     - artifacts\model_training\ridge.joblib
     - artifacts\model_training\svm.joblib

      
       


