parameters:
 fit_intercept: True
 n_jobs: 1
 max_depth: 10
 min_samples_split: 2
 min_samples_leaf: 1
 random_state: 42
 n_estimators: 100
 alpha: 1.0
 max_iter: 1000
 tol: 0.001
 n_neighbors: 5
 weights: uniform
 p: 2
 gamma: auto
 algorithm: auto
 kernel: rbf
 C: 1.0
 epsilon: 0.1