Artifacts_root: artifacts

data_ingestion:
 root_url: artifacts/data_ingestion
 source_url: https://github.com/Robin-star-lab/Taxi_works/raw/refs/heads/main/Zipped_taxi/taxi_trip_pricing.zip
 unzip_data: artifacts/data_ingestion
 local_data_path: artifacts/data_ingestion/data.zip


data_evaluation:
 root_url:  artifacts/data_ingestion
 data_directory:  artifacts/data_ingestion/taxi_trip_pricing.csv
 validation_status: artifacts/data_ingestion/status.txt



data_transformation:
 root_url: artifacts/data_transformation
 data_dir: artifacts/data_ingestion/taxi_trip_pricing.csv


model_training:
 root_url: artifacts/model_training
 train_data: artifacts/data_transformation/train_data.csv

model_evaluation:
 root_url: artifacts/model_evaluation
 evaluation_data: artifacts/data_transformation/test_data.csv
 best_model_path: artifacts/model_evaluation
 decision_tree: artifacts\model_training\decision_tree.joblib
 lasso: artifacts\model_training\lasso.joblib
 linear_regression: artifacts\model_training\linear_regression.joblib
 neighbors: artifacts\model_training\neighbors.joblib
 svm: artifacts\model_training\svm.joblib
 random_forest: artifacts\model_training\random_forest.joblib